---
services:
  traefik:
    image: traefik:v3.6
    secrets:
      - traefik_auth
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

    networks:
      - traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro,Z
      - ./traefik.yaml:/etc/traefik/traefik.yaml:Z
      - /volume1/certs:/certs:ro,Z
      - ./dynamic/:/dynamic:ro,Z

    command:
      # Add General Config (entrypoint, API, providers, basic auth middleware,..)
      - "--configFile=/etc/traefik/traefik.yaml"
      - "--providers.docker=true"

    labels:
      # Enable self‑routing
      - traefik.enable=true

secrets:
  traefik_auth:
    file: ./traefik_auth.txt

networks:
  traefik:
    name: traefik
    external: true


