---
services:
  traefik:
    image: traefik:v3.6
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

    networks:
      - traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro,Z
      - ./traefik.yaml:/etc/traefik/traefik.yaml:Z
      - /volume1/certs:/certs:ro,Z
      - ./dynamic/:/dynamic:ro,Z

    command:
      # Add General Config (entrypoint, API, providers, basic auth middleware,..)
      - "--configFile=/etc/traefik/traefik.yaml"
      - "--providers.docker=true"

  # Traefik Dynamic configuration via Docker labels
    labels:
      # Enable self‑routing
      - traefik.enable=true

      # Dashboard router
      - traefik.http.routers.dashboard.rule=${TRAEFIK_DASHBOARD_RULE}
      - traefik.http.routers.dashboard.entrypoints=websecure
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.tls=true

      # Basic‑auth middleware
      - traefik.http.middlewares.dashboard-auth.basicauth.users=${TRAEFIK_ADMIN_USER}
      - traefik.http.routers.dashboard.middlewares=dashboard-auth@docker
networks:
  traefik:
    name: traefik
    external: true
