---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
data:
  traefik.yaml: |
    entryPoints:
      web:
        address: ":80"
        http:
          redirections:
            entrypoint:
              to: "websecure"
              scheme: "https"
              permanent: "true"
      websecure:
        address: ":443"
        http:
          tls: true
      traefik:
        address: ":8080"

    # Activate dashboard
    api:
      dashboard: true
      insecure: false

    # Watch dynamic configuration folder
    providers:
      docker:
        endpoint: "unix:///var/run/docker.sock"
        exposedByDefault: false
      file:
        directory: /dynamic
        watch: true

    # Logging + Acceslog for debug purposes
    log:
      filePath: "/etc/traefik/traefik.log"
      format: common
      level: DEBUG
    accessLog:
      format: json
      filters:
        statusCodes:
          - "200"
          - "400-404"
          - "500-503"
      fields:
