---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-dynamic-config
data:
  # General traefik dynamic config
  dashboard.yaml: |
    http:
      routers:
        dashboard:
          rule: Host(`dashboard.traefik.lan`)
          entryPoints:
            - websecure
          service: api@internal
          middlewares: secure-headers
          tls: {}

  tls.yaml: |
    tls:
       certificates:
         - certFile: ../certs/traefik-fullchain.crt
           keyFile: ../certs/traefik.key
         - certFile: ../certs/jellyfin.crt
           keyFile: ../certs/jellyfin.key
         - certFile: ../certs/arr-stack-fullchain.crt
           keyFile: ../certs/arr-stack.key

       stores:
        default:
          defaultCertificate:
            certFile: ../certs/traefik-fullchain.crt
            keyFile: ../certs/traefik.key

  middlewares.yaml: |
    http:
       middlewares:
         secure-headers:
           headers:
             contentTypeNosniff: true
             customFrameOptionsValue: SAMEORIGIN

  # Podman services dynamic config
  jellyfin.yaml: |
    http:
      routers:
        jellyfin:
          rule: Host(`jellyfin.lan`)
          entryPoints:
            - websecure
          service: jellyfin
          middlewares:
            - secure-headers@file
      services:
        jellyfin:
          loadBalancer:
            servers:
              - url: http://jellyfin:8096

  arr-stack.yaml: |
    http:
      routers:
        prowlarr:
          rule: Host(`arr-stack.lan`)
          entryPoints:
            - websecure
          service: prowlarr
          tls: {}
          middlewares:
            - secure-headers@file
        sonarr:
          rule: Host(`arr-stack.lan`) && PathPrefix(`/sonarr`)
          entryPoints:
            - websecure
          service: sonarr
          tls: {}
          middlewares:
            - secure-headers@file
        radarr:
          rule: Host(`arr-stack.lan`) && PathPrefix(`/radarr`)
          entryPoints:
            - websecure
          service: radarr
          tls: {}
          middlewares:
            - secure-headers@file
      services:
        prowlarr:
          loadBalancer:
            servers:
              - url: http://prowlarr:9696
        sonarr:
          loadBalancer:
            servers:
              - url: http://sonarr:8989
        radarr:
          loadBalancer:
            servers:
              - url: http://radarr:7878
