---
http:
  routers:
    nas:
      rule: Host(`midgar.lan`)
      entryPoints:
        - websecure
      service: nas
      tls: true
      middlewares:
        - nas-headers

    nas-http:
      rule: Host(`midgar.lan`)
      entryPoints:
        - web
      service: nas
      middlewares:
        - nas-redirect

  services:
    nas:
      loadBalancer:
        servers:
          - url: https://${NAS_IP}:9443
        passHostHeader: true

  middlewares:
    nas-redirect:
      redirectScheme:
        scheme: https

    nas-headers:
      headers:
        contentTypeNosniff: true
        frameDeny: false
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          Host: ${NAS_IP}
