apiVersion: v1
kind: Pod
metadata:
  annotations:
  name: immich
  labels:
    app: immich
spec:
  containers:
    - name: application
      image: ghcr.io/immich-app/immich-server:v2.7.5
      securityContext:
        runAsUser: 1200
        runAsGroup: 1200
        no-new-privileges: true
        capabilities:
          drop:
            - NET_RAW
      env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: DB_URL
        - name: TZ
          value: Europe/Berlin
      ports:
        - port: 2283
          hostPort: 2283
          protocol: TCP
      restartPolicy: Always
      volumeMounts:
        - name: upload-volume
          mountPath: /data
        - name: localtime-volume
          mountPath: /etc/localtime
          readonly: true
    - name: redis
      image: docker.io/valkey/valkey:9
      securityContext:
        runAsUser: 1200
        runAsGroup: 1200
        no-new-privileges: true
        capabilities:
          drop:
            - NET_RAW
      envFrom:
        - configMapRef:
          name: database-configmap
      env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: POSTGRES_PASSWORD
      livenessProbe:
        exec:
          command:
            - redis-cli ping || exit 1
        initialDelaySeconds: 5
        periodSeconds: 5
      volumeMounts:
        - name: redis-volume
          mountPath: /data

    - name: database
      image:  ghcr.io/immich-app/postgres:17-vectorchord0.5.3
      volumeMounts:
        - name: database-volume
          mountPath: /var/lib/postgresql/data
          readOnly: false
      env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_INITDB_ARGS
          value: '--data-checksums'
        - name: POSTGRES_DB
          value: immich
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: POSTGRES_PASSWORD
      securityContext:
        privileged: false
  volumes:
    - name: upload-volume
      hostPath:
        path: /volume1/media/immich/library
        type: Directory
    - name: localtime-volume
      hostPath:
        path: /etc/localtime
        type: Directory
      read_only: true
    - name: redis-volume
      hostPath:
        path: /volume2/containers/immich/redis
        type: Directory
    - name: database-volume
      hostPath:
        path: /volume2/containers/immich/postgres
        type: Directory
