---
http:
  routers:
    jellyfin:
      rule: Host(`jellyfin.lan`)
      entryPoints:
        - websecure
      service: jellyfin
      tls: true
      middlewares:
        - secure-headers

    jellyfin-http:
      rule: Host(`jellyfin.lan`)
      entryPoints:
        - web
      service: jellyfin
      middlewares:
        - jellyfin-redirect

  services:
    jellyfin:
      loadBalancer:
        servers:
          - url: http://jellyfin:8096
        passHostHeader: true

  middlewares:
    jellyfin-redirect:
      redirectScheme:
        scheme: https
