tls:
  certificates:
    - certFile: /certs/traefik-fullchain.crt
      keyFile: /certs/traefik.key
    - certFile: /certs/jellyfin.crt
      keyFile: /certs/jellyfin.key
    - certFile: /certs/arr-stack-fullchain.crt
      keyFile: /certs/arr-stack.key

        #  stores:
        #    default:
        #      defaultCertificate:
        #        certFile: /certs/arr-stack-fullchain.crt #traefik-fullchain.crt
        #        keyFile: /certs/arr-stack.key #traefik.key
