---
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:4.5.5
    container_name: sabnzbd
    restart: unless-stopped
    env_file: ".env"
    volumes:
      - ${CONFIG_PATH}:/config
      - ${DOWNLOAD_PATH}:/downloads
      - ${DOWNLOAD_PATH}/incomplete:/incomplete-downloads
    ports:
      -  4380:8080
