---
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:4.5.5
    container_name: sabnzbd
    restart: unless-stopped
    env_file: ".env"
    volumes:
      - ${CONFIG_PATH}:/config
      - ${DOWNLOAD_PATH}:/downloads
      - ${DOWNLOAD_PATH}/incomplete:/incomplete-downloads
    networks:
      - downloaders
    ports:
      -  4380:8080

networks:
  downloaders:
    name: downloaders
    external: true
