---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:6.0.4
    container_name: radarr
    env_file: ".env"
    networks:
      - traefik
    ports:
      - 7878:7878
    volumes:
      - ${CONFIG_PATH}:/config
      - ${MOVIE_PATH}:/movies
      - ${DOWNLOAD_PATH}:/downloads
    restart: unless-stopped

networks:
  traefik:
    name: traefik
    external: true
