---
services:
   jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: ${PUID}:${PGID}
    group_add:
      - ${GID}
    networks:
      - traefik
    ports:
      - 8096:8096/tcp
    volumes:
      - ${JELLYFIN_ROOT_PATH}/config:/config
      - ${JELLYFIN_ROOT_PATH}/cache:/cache
      - type: bind
        source: ${MEDIA_ROOT}/movies
        target: /movies
        read_only: true
      - type: bind
        source: ${MEDIA_ROOT}/shows
        target: /shows
        read_only: true
      - type: bind
        source: /volume1/jellyfin/fonts
        target: /usr/local/share/fonts/custom
        read_only: true
    restart: 'always'
    healthcheck:
      test: ["CMD", "curl", "-f", "${JELLYFIN_HEALTH}"]
      interval: 1m
      timeout: 30s
      retries: 2
      start_period: 30s
    devices:
      - ${RENDER_DEVICE} 
    labels:
      - "traefik.enable=true"

      ## HTTPS Router
      - traefik.http.routers.jellyfin.rule=${TRAEFIK_ROUTER_HOST}
      - traefik.http.routers.jellyfin.entrypoints=websecure
      - traefik.http.routers.jellyfin.tls=true
    
      ## Service
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
      - traefik.http.services.jellyfin.loadbalancer.passhostheader=true
    
      ## HTTP → HTTPS redirect
      - traefik.http.routers.jellyfin-http.rule=${TRAEFIK_ROUTER_HOST} 
      - traefik.http.routers.jellyfin-http.entrypoints=web
      - traefik.http.routers.jellyfin-http.middlewares=jellyfin-redirect
    
      - traefik.http.middlewares.jellyfin-redirect.redirectscheme.scheme=https
      
      ## Headers
      - traefik.http.routers.jellyfin.middlewares=jellyfin-headers
      - traefik.http.middlewares.jellyfin-headers.headers.contentTypeNosniff=true
      - traefik.http.middlewares.jellyfin-headers.headers.frameDeny=false
      - traefik.http.middlewares.jellyfin-headers.headers.customFrameOptionsValue=SAMEORIGIN

        
        # Optional - alternative address used for autodiscovery
    environment:
      #- JELLYFIN_PublishedServerUrl=https://${JELLYFIN_HOST}
      - TZ=${TZ}
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    # extra_hosts:
      # - 'host.docker.internal:host-gateway'

networks:
  traefik:
    name: traefik
    external: true

