[Interface]
# Bouncing = 6
# NetShield = 1
# Moderates NAT = off
# NAT-PMP (Port-Weiterleitung) = on
# VPN-Accelerator = on
PrivateKey = gDUKZqdUsG1t7w29vE3tknZ6a08xdCp9kGZVN94VyEY=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# CH#436
PublicKey = eFSYPwVvu0LYCDu5LtoJu89FKAXku2ho0JRMCMYswhY=
AllowedIPs = 0.0.0.0/0, ::/0
